// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsAccount "github.com/acme-kuetix/acme-account/modules/account/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["account"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"account"+"/"+"account", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "account", Impl: transitionsAccount.NewAccountTransitions() }})
	}
}
